openapi: 3.2.0
info:
  title: Viator API Documentation & Specification - Affiliate…
  description: 'code { white-space: nowrap; }

    a { font-weight: bold; }


    figure {

    width: 100%;

    text-align: center;

    font-style: italic;

    font-size: smaller;

    text-indent: 0;

    border: thin silver solid;

    margin: 0.5em;

    padding: 0.5em;

    }


    ## Updates


    | Date | Description |

    |------|-------------|

    | 26 May 2022 | Added advice about review authenticity: Key concepts - Review authenticity |

    | 11 Feb 2022 | Added note about no-index policy to /attraction, /attraction/photos, /attraction/reviews and /search/attractions…'
  version: '1.0'
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/au
  contact:
    name: Viator Partner Support Team
    email: affiliateapi@tripadvisor.com
servers:
- url: https://viatorapi.viator.com/service
  description: Production server
security:
- API-key: []
- Legacy-API-key: []
tags:
- name: Utility Services
  description: Utility services
paths:
  /util/sitedetails:
    get:
      tags:
      - Utility Services
      summary: /util/sitedetails
      operationId: utilSitedetails
      description: Get site details – show the site settings for your organization
      parameters:
      - $ref: '#/components/parameters/acceptLanguage'
      - $ref: '#/components/parameters/defaultCurrencyCode'
      - in: query
        name: centralURL
        description: '**URL** for multi-URL sites that have a central URL for processing etc like www.alllasvegastours.com has content.allsightseeingtours.com'
        example: alllasvegastours.com
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/basicErrorModel'
                - type: object
                  properties:
                    data:
                      type: object
                      properties:
                        showLogo:
                          type: boolean
                        showFavicon:
                          type: boolean
                        hasCustomHeaderHtml:
                          type: boolean
                        hasCustomFooterHtml:
                          type: boolean
                        hasCustomCss:
                          type: boolean
                        homepageDestIds:
                          type: boolean
                        piiSetting:
                          type: boolean
                        partnerPrivacyPolicyUrl:
                          type: boolean
                        pointsProgram:
                          type: boolean
                        pointsProgramName:
                          type: boolean
                        pointsProgramUserType:
                          type: boolean
                        pointsProgramHelpText:
                          type: boolean
                        puid:
                          type: boolean
                        retailSiteId:
                          type: boolean
                        companyName:
                          type: boolean
                        defaultCurrency:
                          type: boolean
                        centralURL:
                          type: boolean
                        permissionsDenied:
                          type: array
                          items:
                            type: integer
                        allowMultiCurrency:
                          type: boolean
                        mobileSiteDomain:
                          type: string
                          description: ignore (Viator only)
                        showSupplierName:
                          type: boolean
                        showAllLangServices:
                          type: boolean
                        showPassbook:
                          type: boolean
                        urlPostFixedValue:
                          type: string
                          description: ignore (Viator only)
                        canDisableBookEmail:
                          type: boolean
                        clientId:
                          type: string
                        locale:
                          type: string
                        enabled:
                          type: boolean
                        url:
                          type: string
                        id:
                          type: integer
                        channel:
                          type: string
              examples:
                '1':
                  $ref: '#/components/examples/util-sitedetails-example'
  /util/countrymap:
    get:
      tags:
      - Utility Services
      summary: /util/countrymap
      operationId: utilCountrymap
      description: Get a dictionary mapping coutry-codes to their natural-language names and international dialling prefixes
      parameters:
      - $ref: '#/components/parameters/acceptLanguage'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/basicErrorModel'
                - type: object
                  properties:
                    data:
                      type: object
                      properties:
                        AF:
                          type: object
                          properties:
                            countryName:
                              type: string
                              description: '**natural-language name** of the country that the country-code identifies'
                            phoneCode:
                              type: string
                              description: '**[International Direct Dialling (IDD)](https://en.wikipedia.org/wiki/International_direct_dialing) prefix** for the country in question'
                            countryId:
                              type: string
                              description: '**country-code** for the country in question'
                        AX:
                          type: object
                          properties:
                            countryName:
                              type: string
                              description: '**natural-language name** of the country that the country-code identifies'
                            phoneCode:
                              type: string
                              description: '**[International Direct Dialling (IDD)](https://en.wikipedia.org/wiki/International_direct_dialing) prefix** for the country in question'
                            countryId:
                              type: string
                              description: '**country-code** for the country in question'
              examples:
                '1':
                  $ref: '#/components/examples/util-countrymap-example'
  /util/guid:
    get:
      tags:
      - Utility Services
      summary: /util/guid
      operationId: utilGuid
      description: This service can be used to generate a GUID if necessary
      parameters:
      - $ref: '#/components/parameters/acceptLanguage'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/basicErrorModel'
                - type: object
                  properties:
                    data:
                      type: string
                      description: '**[GUID (globally unique identifier)](https://en.wikipedia.org/wiki/Universally_unique_identifier)** for the request'
              examples:
                '1':
                  $ref: '#/components/examples/util-guid-example'
  /util/siteBinaryData:
    post:
      tags:
      - Utility Services
      summary: /util/siteBinaryData
      operationId: utilSiteBinaryData
      description: Get partner custom information, such as Logo, Favicon or quick links (only necessary for some partners)
      parameters:
      - $ref: '#/components/parameters/acceptLanguage'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                partnerCustomTypes:
                  type: array
                  items:
                    type: string
                    enum:
                    - LOGO
                    - LOGO_URL
                    - FAVICON
                    - HEADER_HTML
                    - FOOTER_HTML
                    - CSS
                  description: '- `LOGO` - show base64-encoded data of partner''s logo

                    - `LOGO_URL` - show base64-encoded data of partner''s logo URL

                    - `FAVICON` - show base64-encoded data of partner''s favicon

                    - `HEADER_HTML` - show base64-encoded data of the partner''s header HTML

                    - `FOOTER_HTML` - show base64-encoded data of the partner''s footer HTML

                    - `CSS` - show base64 based data of partner Site CSS

                    '
                  example:
                  - LOGO
                  - LOGO_URL
                  - FAVICON
                  - HEADER_HTML
                  - FOOTER_HTML
                  - CSS
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/basicErrorModel'
                - type: object
                  properties:
                    data:
                      type: object
                      properties:
                        favicon:
                          type: string
                          description: '**base64-encoded image** of the partner''s favicon'
                        logo:
                          type: string
                          description: '**base64-encoded image** of the partner''s logo'
                        logoUrl:
                          type: string
                          description: '**base64-encoded data** of the partner''s logo URL'
                        headerHtml:
                          type: string
                          description: '**base64-encoded data** of the partner sites header HTML'
                        footerHtml:
                          type: string
                          description: '**base64-encoded data** of the partner site''s footer HTMl'
                        css:
                          type: string
                          description: '**base64-encoded image** of the partner''s site''s CSS'
              examples:
                '1':
                  $ref: '#/components/examples/util-siteBinaryData-example'
components:
  examples:
    util-guid-example:
      summary: /util/guid
      value:
        errorReference: null
        data: 331003-1969648698962354-6150751091453490107
        dateStamp: 2020-04-21T17:14:06+0000
        errorType: null
        errorCodes: []
        errorMessage: null
        errorName: null
        extraInfo: {}
        extraObject: null
        success: true
        totalCount: 1
        errorMessageText: null
        vmid: '331003'
    util-sitedetails-example:
      summary: /util/sitedetails
      value:
        errorReference: null
        data:
          showLogo: false
          showFavicon: false
          hasCustomHeaderHtml: false
          hasCustomFooterHtml: false
          hasCustomCss: false
          homepageDestIds: []
          piiSetting: NO_PII
          partnerPrivacyPolicyUrl: ''
          pointsProgram: false
          pointsProgramName: ''
          pointsProgramUserType: ''
          pointsProgramHelpText: ''
          puid: '00000'
          retailSiteId: 00000.api.partner.viator.com
          companyName: TheName
          defaultCurrency: USD
          centralURL: shop.live.rc.viator.com
          permissionsDenied:
          - 1
          - 42
          - 75
          - 46
          - 78
          - 15
          - 82
          - 116
          - 53
          - 85
          - 22
          - 118
          - 119
          - 120
          - 121
          allowMultiCurrency: false
          mobileSiteDomain: null
          showSupplierName: false
          showAllLangServices: false
          showPassbook: false
          urlPostFixedValue: eap=brand-subbrand-00000&aid=vba00000en
          canDisableBookEmail: false
          clientId: PARTNER:API-en:VBA:00000
          locale: en
          enabled: true
          url: shop.live.rc.viator.com
          id: 0
          channel: PARTNER
        dateStamp: 2020-04-21T17:22:00+0000
        errorType: null
        errorCodes: []
        errorMessage: null
        errorName: null
        extraInfo: {}
        extraObject: null
        success: true
        totalCount: 1
        errorMessageText: null
        vmid: '331003'
    util-countrymap-example:
      summary: /util/countrymap
      value:
        errorReference: null
        data:
          AF:
            phoneCode: '+93'
            countryName: Afghanistan
            countryId: AF
          AX:
            phoneCode: '+358'
            countryName: Aland Islands
            countryId: AX
          AL:
            phoneCode: '+355'
            countryName: Albania
            countryId: AL
          DZ:
            phoneCode: '+213'
            countryName: Algeria
            countryId: DZ
          AS:
            phoneCode: +1-684
            countryName: American Samoa
            countryId: AS
          AD:
            phoneCode: '+376'
            countryName: Andorra
            countryId: AD
          AO:
            phoneCode: '+244'
            countryName: Angola
            countryId: AO
          AI:
            phoneCode: +1-264
            countryName: Anguilla
            countryId: AI
          AQ:
            phoneCode: '+672'
            countryName: Antarctica
            countryId: AQ
          AG:
            phoneCode: +1-268
            countryName: Antigua and Barbuda
            countryId: AG
          AR:
            phoneCode: '+54'
            countryName: Argentina
            countryId: AR
          AM:
            phoneCode: '+374'
            countryName: Armenia
            countryId: AM
          AW:
            phoneCode: '+297'
            countryName: Aruba
            countryId: AW
          AC:
            phoneCode: ''
            countryName: Ascension
            countryId: AC
          AU:
            phoneCode: '+61'
            countryName: Australia
            countryId: AU
          AT:
            phoneCode: '+43'
            countryName: Austria
            countryId: AT
          AZ:
            phoneCode: '+994'
            countryName: Azerbaijan
            countryId: AZ
          BS:
            phoneCode: +1-242
            countryName: Bahamas
            countryId: BS
          BH:
            phoneCode: '+973'
            countryName: Bahrain
            countryId: BH
          BD:
            phoneCode: '+880'
            countryName: Bangladesh
            countryId: BD
          BB:
            phoneCode: +1-246
            countryName: Barbados
            countryId: BB
          BY:
            phoneCode: '+375'
            countryName: Belarus
            countryId: BY
          BE:
            phoneCode: '+32'
            countryName: Belgium
            countryId: BE
          BZ:
            phoneCode: '+501'
            countryName: Belize
            countryId: BZ
          BJ:
            phoneCode: '+229'
            countryName: Benin
            countryId: BJ
          BM:
            phoneCode: +1-441
            countryName: Bermuda
            countryId: BM
          BT:
            phoneCode: '+975'
            countryName: Bhutan
            countryId: BT
          BO:
            phoneCode: '+591'
            countryName: Bolivia
            countryId: BO
          BQ:
            phoneCode: '+599'
            countryName: Bonaire
            countryId: BQ
          BA:
            phoneCode: '+387'
            countryName: Bosnia and Herzegovina
            countryId: BA
          BW:
            phoneCode: '+267'
            countryName: Botswana
            countryId: BW
          BV:
            phoneCode: '+55'
            countryName: Bouvet Island
            countryId: BV
          BR:
            phoneCode: '+55'
            countryName: Brazil
            countryId: BR
          IO:
            phoneCode: '+246'
            countryName: British Indian Ocean Territory
            countryId: IO
          BN:
            phoneCode: '+673'
            countryName: Brunei Darussalam
            countryId: BN
          BG:
            phoneCode: '+359'
            countryName: Bulgaria
            countryId: BG
          BF:
            phoneCode: '+226'
            countryName: Burkina Faso
            countryId: BF
          XX:
            phoneCode: ''
            countryName: Burma (refer to Myanmar)
            countryId: XX
          BI:
            phoneCode: '+257'
            countryName: Burundi
            countryId: BI
          CV:
            phoneCode: '+238'
            countryName: Cabo Verde
            countryId: CV
          KH:
            phoneCode: '+855'
            countryName: Cambodia
            countryId: KH
          CM:
            phoneCode: '+237'
            countryName: Cameroon
            countryId: CM
          CA:
            phoneCode: '+1'
            countryName: Canada
            countryId: CA
          BQN:
            phoneCode: ''
            countryName: Caribbean Netherlands
            countryId: BQN
          KY:
            phoneCode: +1-345
            countryName: Cayman Islands
            countryId: KY
          CF:
            phoneCode: '+236'
            countryName: Central African Republic
            countryId: CF
          TD:
            phoneCode: '+235'
            countryName: Chad
            countryId: TD
          CL:
            phoneCode: '+56'
            countryName: Chile
            countryId: CL
          CN:
            phoneCode: '+86'
            countryName: China
            countryId: CN
          CX:
            phoneCode: '+61'
            countryName: Christmas Island
            countryId: CX
          CC:
            phoneCode: '+61'
            countryName: Cocos (Keeling) Islands
            countryId: CC
          CO:
            phoneCode: '+57'
            countryName: Colombia
            countryId: CO
          KM:
            phoneCode: '+269'
            countryName: Comoros
            countryId: KM
          CK:
            phoneCode: '+682'
            countryName: Cook Islands
            countryId: CK
          CR:
            phoneCode: '+506'
            countryName: Costa Rica
            countryId: CR
          CI:
            phoneCode: '+225'
            countryName: Cote d'Ivoire
            countryId: CI
          HR:
            phoneCode: '+385'
            countryName: Croatia
            countryId: HR
          CW:
            phoneCode: '+599'
            countryName: Curacao
            countryId: CW
          CY:
            phoneCode: '+357'
            countryName: Cyprus
            countryId: CY
          CZ:
            phoneCode: '+420'
            countryName: Czechia
            countryId: CZ
          DK:
            phoneCode: '+45'
            countryName: Denmark
            countryId: DK
          DJ:
            phoneCode: '+253'
            countryName: Djibouti
            countryId: DJ
          DM:
            phoneCode: +1-767
            countryName: Dominica
            countryId: DM
          DO:
            phoneCode: +1-809
            countryName: Dominican Republic
            countryId: DO
          EC:
            phoneCode: '+593'
            countryName: Ecuador
            countryId: EC
          EG:
            phoneCode: '+20'
            countryName: Egypt
            countryId: EG
          SV:
            phoneCode: '+503'
            countryName: El Salvador
            countryId: SV
          GQ:
            phoneCode: '+240'
            countryName: Equatorial Guinea
            countryId: GQ
          ER:
            phoneCode: '+291'
            countryName: Eritrea
            countryId: ER
          EE:
            phoneCode: '+372'
            countryName: Estonia
            countryId: EE
          ET:
            phoneCode: '+251'
            countryName: Ethiopia
            countryId: ET
          FK:
            phoneCode: '+500'
            countryName: Falkland Islands
            countryId: FK
          FO:
            phoneCode: '+298'
            countryName: Faroe Islands
            countryId: FO
          FJ:
            phoneCode: '+679'
            countryName: Fiji
            countryId: FJ
          FI:
            phoneCode: '+358'
            countryName: Finland
            countryId: FI
          FR:
            phoneCode: '+33'
            countryName: France
            countryId: FR
          GF:
            phoneCode: '+594'
            countryName: French Guiana
            countryId: GF
          PF:
            phoneCode: '+689'
            countryName: French Polynesia
            countryId: PF
          TF:
            phoneCode: '+262'
            countryName: French Southern Territories and Antarctic Lands
            countryId: TF
          GA:
            phoneCode: '+241'
            countryName: Gabon
            countryId: GA
          GM:
            phoneCode: '+220'
            countryName: Gambia
            countryId: GM
          GE:
            phoneCode: '+995'
            countryName: Georgia
            countryId: GE
          DE:
            phoneCode: '+49'
            countryName: Germany
            countryId: DE
          GH:
            phoneCode: '+233'
            countryName: Ghana
            countryId: GH
          GI:
            phoneCode: '+350'
            countryName: Gibraltar
            countryId: GI
          GR:
            phoneCode: '+30'
            countryName: Greece
            countryId: GR
          GL:
            phoneCode: '+299'
            countryName: Greenland
            countryId: GL
          GD:
            phoneCode: +1-473
            countryName: Grenada
            countryId: GD
          GP:
            phoneCode: '+590'
            countryName: Guadeloupe
            countryId: GP
          GU:
            phoneCode: +1-671
            countryName: Guam
            countryId: GU
          GT:
            phoneCode: '+502'
            countryName: Guatemala
            countryId: GT
          GG:
            phoneCode: +44-1481
            countryName: Guernsey
            countryId: GG
          GN:
            phoneCode: '+224'
            countryName: Guinea
            countryId: GN
          GW:
            phoneCode: '+245'
            countryName: Guinea-Bissau
            countryId: GW
          GY:
            phoneCode: '+592'
            countryName: Guyana
            countryId: GY
          HT:
            phoneCode: '+509'
            countryName: Haiti
            countryId: HT
          HM:
            phoneCode: '+61'
            countryName: Heard Island and McDonald Islands
            countryId: HM
          VA:
            phoneCode: '+379'
            countryName: Holy See (Vatican City State)
            countryId: VA
          HN:
            phoneCode: '+504'
            countryName: Honduras
            countryId: HN
          HK:
            phoneCode: '+852'
            countryName: Hong Kong
            countryId: HK
          HU:
            phoneCode: '+36'
            countryName: Hungary
            countryId: HU
          IS:
            phoneCode: '+354'
            countryName: Iceland
            countryId: IS
          IN:
            phoneCode: '+91'
            countryName: India
            countryId: IN
          ID:
            phoneCode: '+62'
            countryName: Indonesia
            countryId: ID
          IQ:
            phoneCode: ''
            countryName: Iraq
            countryId: IQ
          IE:
            phoneCode: '+353'
            countryName: Ireland
            countryId: IE
          IM:
            phoneCode: +44-1624
            countryName: Isle of Man
            countryId: IM
          IL:
            phoneCode: '+972'
            countryName: Israel
            countryId: IL
          IT:
            phoneCode: '+39'
            countryName: Italy
            countryId: IT
          JM:
            phoneCode: +1-876
            countryName: Jamaica
            countryId: JM
          JP:
            phoneCode: '+81'
            countryName: Japan
            countryId: JP
          JE:
            phoneCode: +44-1534
            countryName: Jersey
            countryId: JE
          JO:
            phoneCode: '+962'
            countryName: Jordan
            countryId: JO
          KZ:
            phoneCode: '+7'
            countryName: Kazakhstan
            countryId: KZ
          KE:
            phoneCode: '+254'
            countryName: Kenya
            countryId: KE
          KI:
            phoneCode: '+686'
            countryName: Kiribati
            countryId: KI
          KW:
            phoneCode: '+965'
            countryName: Kuwait
            countryId: KW
          KG:
            phoneCode: '+996'
            countryName: Kyrgyzstan
            countryId: KG
          LA:
            phoneCode: '+856'
            countryName: Lao People's Democratic Republic
            countryId: LA
          LV:
            phoneCode: '+371'
            countryName: Latvia
            countryId: LV
          LB:
            phoneCode: '+961'
            countryName: Lebanon
            countryId: LB
          LS:
            phoneCode: '+266'
            countryName: Lesotho
            countryId: LS
          LR:
            phoneCode: '+231'
            countryName: Liberia
            countryId: LR
          LY:
            phoneCode: '+218'
            countryName: Libya
            countryId: LY
          LI:
            phoneCode: '+423'
            countryName: Liechtenstein
            countryId: LI
          LT:
            phoneCode: '+370'
            countryName: Lithuania
            countryId: LT
          LU:
            phoneCode: '+352'
            countryName: Luxembourg
            countryId: LU
          MO:
            phoneCode: '+853'
            countryName: Macao
            countryId: MO
          MK:
            phoneCode: '+389'
            countryName: Macedonia
            countryId: MK
          MG:
            phoneCode: '+261'
            countryName: Madagascar
            countryId: MG
          MW:
            phoneCode: '+265'
            countryName: Malawi
            countryId: MW
          MY:
            phoneCode: '+60'
            countryName: Malaysia
            countryId: MY
          MV:
            phoneCode: '+960'
            countryName: Maldives
            countryId: MV
          ML:
            phoneCode: '+223'
            countryName: Mali
            countryId: ML
          MT:
            phoneCode: '+356'
            countryName: Malta
            countryId: MT
          MQ:
            phoneCode: '+596'
            countryName: Martinique
            countryId: MQ
          MR:
            phoneCode: '+222'
            countryName: Mauritania
            countryId: MR
          MU:
            phoneCode: '+230'
            countryName: Mauritius
            countryId: MU
          YT:
            phoneCode: '+269'
            countryName: Mayotte
            countryId: YT
          MX:
            phoneCode: '+52'
            countryName: Mexico
            countryId: MX
          FM:
            phoneCode: '+691'
            countryName: Micronesia
            countryId: FM
          MD:
            phoneCode: '+373'
            countryName: Moldova
            countryId: MD
          MC:
            phoneCode: '+377'
            countryName: Monaco
            countryId: MC
          MN:
            phoneCode: '+976'
            countryName: Mongolia
            countryId: MN
          ME:
            phoneCode: '+382'
            countryName: Montenegro
            countryId: ME
          MS:
            phoneCode: +1-664
            countryName: Montserrat
            countryId: MS
          MA:
            phoneCode: '+212'
            countryName: Morocco
            countryId: MA
          MZ:
            phoneCode: '+258'
            countryName: Mozambique
            countryId: MZ
          MM:
            phoneCode: '+95'
            countryName: Myanmar
            countryId: MM
          NA:
            phoneCode: '+264'
            countryName: Namibia
            countryId: NA
          NR:
            phoneCode: '+674'
            countryName: Nauru
            countryId: NR
          NP:
            phoneCode: '+977'
            countryName: Nepal
            countryId: NP
          NL:
            phoneCode: '+31'
            countryName: Netherlands
            countryId: NL
          AN:
            phoneCode: '+599'
            countryName: Netherlands Antilles
            countryId: AN
          NC:
            phoneCode: '+687'
            countryName: New Caledonia
            countryId: NC
          NZ:
            phoneCode: '+64'
            countryName: New Zealand
            countryId: NZ
          NI:
            phoneCode: '+505'
            countryName: Nicaragua
            countryId: NI
          NE:
            phoneCode: '+227'
            countryName: Niger
            countryId: NE
          NG:
            phoneCode: '+234'
            countryName: Nigeria
            countryId: NG
          NU:
            phoneCode: '+683'
            countryName: Niue
            countryId: NU
          NF:
            phoneCode: '+672'
            countryName: Norfolk Island
            countryId: NF
          MP:
            phoneCode: +1-670
            countryName: Northern Mariana Islands
            countryId: MP
          'NO':
            phoneCode: '+47'
            countryName: Norway
            countryId: 'NO'
          OM:
            phoneCode: '+968'
            countryName: Oman
            countryId: OM
          PK:
            phoneCode: '+92'
            countryName: Pakistan
            countryId: PK
          PW:
            phoneCode: '+680'
            countryName: Palau
            countryId: PW
          PS:
            phoneCode: '+970'
            countryName: Palestine, State of
            countryId: PS
          PA:
            phoneCode: '+507'
            countryName: Panama
            countryId: PA
          PG:
            phoneCode: '+675'
            countryName: Papua New Guinea
            countryId: PG
          PY:
            phoneCode: '+595'
            countryName: Paraguay
            countryId: PY
          PE:
            phoneCode: '+51'
            countryName: Peru
            countryId: PE
          PH:
            phoneCode: '+63'
            countryName: Philippines
            countryId: PH
          PN:
            phoneCode: '+64'
            countryName: Pitcairn
            countryId: PN
          PL:
            phoneCode: '+48'
            countryName: Poland
            countryId: PL
          PT:
            phoneCode: '+351'
            countryName: Portugal
            countryId: PT
          PR:
            phoneCode: '+1'
            countryName: Puerto Rico
            countryId: PR
          QA:
            phoneCode: '+974'
            countryName: Qatar
            countryId: QA
          RE:
            phoneCode: '+262'
            countryName: Reunion
            countryId: RE
          RO:
            phoneCode: '+40'
            countryName: Romania
            countryId: RO
          RU:
            phoneCode: '+7'
            countryName: Russian Federation
            countryId: RU
          RW:
            phoneCode: '+250'
            countryName: Rwanda
            countryId: RW
          BQS:
            phoneCode: ''
            countryName: Saba
            countryId: BQS
          SH:
            phoneCode: '+290'
            countryName: Saint Helena
            countryId: SH
          KN:
            phoneCode: +1-869
            countryName: Saint Kitts and Nevis
            countryId: KN
          LC:
            phoneCode: +1-758
            countryName: Saint Lucia
            countryId: LC
          MF:
            phoneCode: '+590'
            countryName: Saint Martin
            countryId: MF
          PM:
            phoneCode: '+508'
            countryName: Saint Pierre and Miquelon
            countryId: PM
          WS:
            phoneCode: '+685'
            countryName: Samoa
            countryId: WS
          SM:
            phoneCode: '+378'
            countryName: San Marino
            countryId: SM
          ST:
            phoneCode: '+239'
            countryName: Sao Tome and Principe
            countryId: ST
          SA:
            phoneCode: '+966'
            countryName: Saudi Arabia
            countryId: SA
          SN:
            phoneCode: '+221'
            countryName: Senegal
            countryId: SN
          RS:
            phoneCode: '+381'
            countryName: Serbia
            countryId: RS
          YU:
            phoneCode: '+381'
            countryName: Serbia and Montenegro
            countryId: YU
          SC:
            phoneCode: '+248'
            countryName: Seychelles
            countryId: SC
          SL:
            phoneCode: '+232'
            countryName: Sierra Leone
            countryId: SL
          SG:
            phoneCode: '+65'
            countryName: Singapore
            countryId: SG
          SX:
            phoneCode: '+1721'
            countryName: Sint Maarten
            countryId: SX
          SK:
            phoneCode: '+421'
            countryName: Slovakia
            countryId: SK
          SI:
            phoneCode: '+386'
            countryName: Slovenia
            countryId: SI
          SB:
            phoneCode: '+677'
            countryName: Solomon Islands
            countryId: SB
          SO:
            phoneCode: '+252'
            countryName: Somalia
            countryId: SO
          ZA:
            phoneCode: '+27'
            countryName: South Africa
            countryId: ZA
          KR:
            phoneCode: '+82'
            countryName: South Korea
            countryId: KR
          ES:
            phoneCode: '+34'
            countryName: Spain
            countryId: ES
          LK:
            phoneCode: '+94'
            countryName: Sri Lanka
            countryId: LK
          VC:
            phoneCode: +1-784
            countryName: St Vincent and Grenadines
            countryId: VC
          SR:
            phoneCode: '+597'
            countryName: Suriname
            countryId: SR
          SZ:
            phoneCode: '+268'
            countryName: Swaziland
            countryId: SZ
          SE:
            phoneCode: '+46'
            countryName: Sweden
            countryId: SE
          CH:
            phoneCode: '+41'
            countryName: Switzerland
            countryId: CH
          TW:
            phoneCode: '+886'
            countryName: Taiwan
            countryId: TW
          TJ:
            phoneCode: '+992'
            countryName: Tajikistan
            countryId: TJ
          TZ:
            phoneCode: '+255'
            countryName: Tanzania, United Republic of
            countryId: TZ
          TH:
            phoneCode: '+66'
            countryName: Thailand
            countryId: TH
          TL:
            phoneCode: '+670'
            countryName: Timor-Leste
            countryId: TL
          TG:
            phoneCode: '+228'
            countryName: Togo
            countryId: TG
          TK:
            phoneCode: '+690'
            countryName: Tokelau
            countryId: TK
          TO:
            phoneCode: '+676'
            countryName: Tonga
            countryId: TO
          TT:
            phoneCode: +1-868
            countryName: Trinidad and Tobago
            countryId: TT
          TN:
            phoneCode: '+216'
            countryName: Tunisia
            countryId: TN
          TR:
            phoneCode: '+90'
            countryName: Turkey
            countryId: TR
          TM:
            phoneCode: '+993'
            countryName: Turkmenistan
            countryId: TM
          TC:
            phoneCode: +1-649
            countryName: Turks and Caicos Islands
            countryId: TC
          TV:
            phoneCode: '+688'
            countryName: Tuvalu
            countryId: TV
          UG:
            phoneCode: '+256'
            countryName: Uganda
            countryId: UG
          UA:
            phoneCode: '+380'
            countryName: Ukraine
            countryId: UA
          AE:
            phoneCode: '+971'
            countryName: United Arab Emirates
            countryId: AE
          GB:
            phoneCode: '+44'
            countryName: United Kingdom
            countryId: GB
          UM:
            phoneCode: '+1'
            countryName: United States Minor Outlying Islands
            countryId: UM
          US:
            phoneCode: '+1'
            countryName: United States of America
            countryId: US
          UY:
            phoneCode: '+598'
            countryName: Uruguay
            countryId: UY
          UZ:
            phoneCode: '+998'
            countryName: Uzbekistan
            countryId: UZ
          VU:
            phoneCode: '+678'
            countryName: Vanuatu
            countryId: VU
          VE:
            phoneCode: '+58'
            countryName: Venezuela
            countryId: VE
          VN:
            phoneCode: '+84'
            countryName: Viet Nam
            countryId: VN
          VG:
            phoneCode: +1-284
            countryName: Virgin Islands (British)
            countryId: VG
          VI:
            phoneCode: +1-340
            countryName: Virgin Islands (U.S.)
            countryId: VI
          WF:
            phoneCode: '+681'
            countryName: Wallis and Futuna
            countryId: WF
          YE:
            phoneCode: '+967'
            countryName: Yemen
            countryId: YE
          ZM:
            phoneCode: '+260'
            countryName: Zambia
            countryId: ZM
          ZW:
            phoneCode: '+263'
            countryName: Zimbabwe
            countryId: ZW
        dateStamp: 2020-04-21T17:10:10+0000
        errorType: null
        errorCodes: []
        errorMessage: null
        errorName: null
        extraInfo: {}
        extraObject: null
        success: true
        totalCount: 1
        errorMessageText: null
        vmid: '331001'
    util-siteBinaryData-example:
      summary: /util/siteBinaryData
      value:
        errorReference: null
        data:
          favicon: null
          logo: null
          logoUrl: null
          headerHtml: null
          footerHtml: null
          css: null
        dateStamp: 2020-04-21T17:20:24+0000
        errorType: null
        errorCodes: []
        errorMessage: null
        errorName: null
        extraInfo: {}
        extraObject: null
        success: true
        totalCount: 1
        errorMessageText: null
        vmid: '331001'
  schemas:
    basicErrorModel:
      type: object
      properties:
        errorReference:
          type: string
          example: null
          description: '**reference number** of *this* error'
        dateStamp:
          type: string
          example: 2017-11-24T21:30:47+0000
          description: '**timestamp** of *this* response'
        errorType:
          type: string
          description: '**code** specifying the type of error'
          example: null
        errorCodes:
          type: array
          description: '**array** of error codes pertaining to *this* error

            - See: [Exception error codes](#section/Appendices/Exception-error-codes) for a list of possible error codes

            '
          items:
            type: string
          example: []
        errorMessage:
          type: array
          description: '**array** of error message strings'
          example: null
        errorName:
          type: string
          example: null
          description: '**name** of *this* type of error'
        extraInfo:
          type: object
          description: ignore (Viator only)
        extraObject:
          type: object
          description: ignore (Viator only)
        success:
          type: boolean
          example: true
          description: '**boolean indicator** of *this* request''s outcome

            - `true`: the request was successful with no errors

            - `false`: an error was encountered

            '
        totalCount:
          type: integer
          example: 1
          description: '**number** of results available for *this* service

            '
        errorMessageText:
          type: string
          example: null
          description: '**array** of error message strings in plain text'
        vmid:
          type: string
          example: '321050'
          description: '**unique numeric id** of the server that processed *this* request'
  parameters:
    defaultCurrencyCode:
      name: defaultCurrencyCode
      in: query
      description: '**currency code** (default) for pricing

        - countries with standard currencies will default to *this* currency for pricing display prices displayed in this currency as the default currency

        - other countries will default to `''USD''`

        - e.g., Australia would be `''AUD''`; Vietnam would be `''USD''`

        - See: [supported currencies](#section/Appendices/Supported-currency-codes)

        '
      schema:
        type: string
      example: USD
    acceptLanguage:
      in: header
      name: Accept-Language
      description: 'Specifies the language into which the natural-language fields in the response from this service will be translated (see [Accept-Language header](#section/Appendices/Accept-Language-header) for available language codes)

        '
      required: true
      schema:
        type: string
  securitySchemes:
    Legacy-API-key:
      type: apiKey
      in: query
      name: apiKey
    API-key:
      type: apiKey
      in: header
      name: exp-api-key
